#!/bin/bash
# Dirfor:
# Ouput directories in use, with PIDs for a given process name.
# Useful when a process has gone out of control and you need to
# kill it, but are not sure of the PID.
#
# Usage:
# dirfor ruby
# dirfor vim
#
ps axc |
awk "/$1/"'{print  $1}' |
xargs -L1 lsof -p |
awk '/DIR/ { pids[$2] = $NF }
     END {
           for (pid in pids)
             print pid,"is in", pids[pid]
         }'
