#!/bin/bash
# ps axc for process
ps axc |

# awk for PID & name
awk "/$1/"'{print  $1}' |

# lfof -pf for PIDs files
xargs -L1 lsof -p |

# awk for output
awk '/DIR/ { pids[$2] = $NF }
     END {
           for (pid in pids)
             print pid,"is in", pids[pid]
         }'
